name: demo action

on: 
  push:
    branches:
      -main
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build"

  test:
    runs-on: ubuntu-latest  # Fixed typo (was 'uduntu-latest')
    needs: build
    steps: 
      - name: Test
        run: echo "TEST"
